// This file is auto-generated by @hey-api/openapi-ts

import type {
  Client,
  ClientMeta,
  Options as Options2,
  RequestResult,
  TDataShape,
} from "./client";
import { client } from "./client.gen";
import type {
  CheckSharePostRankData,
  CheckSharePostRankErrors,
  CheckSharePostRankResponses,
  CreateActivityData,
  CreateActivityErrors,
  CreateActivityResponses,
  CreateApiErrorData,
  CreateApiErrorErrors,
  CreateApiErrorResponses,
  CreateBookmarkData,
  CreateBookmarkErrors,
  CreateBookmarkResponses,
  CreateBusinessesResAvailabilityData,
  CreateBusinessesResAvailabilityErrors,
  CreateBusinessesResAvailabilityResponses,
  CreateChallengeProgressShareData,
  CreateChallengeProgressShareErrors,
  CreateChallengeProgressShareResponses,
  CreateDataUserBusinessTextData,
  CreateDataUserBusinessTextErrors,
  CreateDataUserBusinessTextResponses,
  CreateFilterListData,
  CreateFilterListErrors,
  CreateFilterListResponses,
  CreateFilterOptionsData,
  CreateFilterOptionsErrors,
  CreateFilterOptionsResponses,
  CreateFollowData,
  CreateFollowErrors,
  CreateFollowResponses,
  CreatePassedUserCorrData,
  CreatePassedUserCorrErrors,
  CreatePassedUserCorrResponses,
  CreateRankingData,
  CreateRankingErrors,
  CreateRankingResponses,
  CreateUserHscrollListsPlacementData,
  CreateUserHscrollListsPlacementErrors,
  CreateUserHscrollListsPlacementResponses,
  CreateUserListData,
  CreateUserListErrors,
  CreateUserListResponses,
  CreateUserRecScoresData,
  CreateUserRecScoresErrors,
  CreateUserRecScoresResponses,
  CreateUserSettingData,
  CreateUserSettingErrors,
  CreateUserSettingResponses,
  DeleteRankingData,
  DeleteRankingErrors,
  DeleteRankingResponses,
  GetAggFollowingNewData,
  GetAggFollowingNewErrors,
  GetAggFollowingNewResponses,
  GetAllCitiesData,
  GetAllCitiesErrors,
  GetAllCitiesResponses,
  GetAppleMapsTokenData,
  GetAppleMapsTokenErrors,
  GetAppleMapsTokenResponses,
  GetAppNotificationData,
  GetAppNotificationErrors,
  GetAppNotificationResponses,
  GetAppRankData,
  GetAppRankErrors,
  GetAppRankResponses,
  GetAvailableReservationsData,
  GetAvailableReservationsErrors,
  GetAvailableReservationsResponses,
  GetBannerNotificationData,
  GetBannerNotificationErrors,
  GetBannerNotificationResponses,
  GetBlockedData,
  GetBlockedErrors,
  GetBlockedMeData,
  GetBlockedMeErrors,
  GetBlockedMeResponses,
  GetBlockedResponses,
  GetBookmarkData,
  GetBookmarkErrors,
  GetBookmarkResponses,
  GetBookmarkStatusData,
  GetBookmarkStatusErrors,
  GetBookmarkStatusResponses,
  GetBusinessCountRatedData,
  GetBusinessCountRatedErrors,
  GetBusinessCountRatedResponses,
  GetBusinessData,
  GetBusinessErrors,
  GetBusinessFriendTextData,
  GetBusinessFriendTextErrors,
  GetBusinessFriendTextResponses,
  GetBusinessHistogramDataData,
  GetBusinessHistogramDataErrors,
  GetBusinessHistogramDataResponses,
  GetBusinessLabelsData,
  GetBusinessLabelsErrors,
  GetBusinessLabelsResponses,
  GetBusinessLinkData,
  GetBusinessLinkErrors,
  GetBusinessLinkResponses,
  GetBusinessResBookedListData,
  GetBusinessResBookedListErrors,
  GetBusinessResBookedListResponses,
  GetBusinessResponses,
  GetChallengeJoinConfigData,
  GetChallengeJoinConfigErrors,
  GetChallengeJoinConfigResponses,
  GetCheckUserSettingsData,
  GetCheckUserSettingsErrors,
  GetCheckUserSettingsResponses,
  GetClosedatauserbusinessbooleanData,
  GetClosedatauserbusinessbooleanErrors,
  GetClosedatauserbusinessbooleanResponses,
  GetCorrData,
  GetCorrErrors,
  GetCorrResponses,
  GetCountAppNotificationUnreadData,
  GetCountAppNotificationUnreadErrors,
  GetCountAppNotificationUnreadResponses,
  GetCountRankedThisYearData,
  GetCountRankedThisYearErrors,
  GetCountRankedThisYearResponses,
  GetCountuserbusinessoccasionData,
  GetCountuserbusinessoccasionErrors,
  GetCountuserbusinessoccasionResponses,
  GetCreatorSubscribeData,
  GetCreatorSubscribeErrors,
  GetCreatorSubscribeResponses,
  GetCuisineAllCuisinesData,
  GetCuisineAllCuisinesErrors,
  GetCuisineAllCuisinesResponses,
  GetCurrentCityData,
  GetCurrentCityErrors,
  GetCurrentCityResponses,
  GetDatabusinessfloatSparseData,
  GetDatabusinessfloatSparseErrors,
  GetDatabusinessfloatSparseResponses,
  GetDatauserbusinesstextSparseData,
  GetDatauserbusinesstextSparseErrors,
  GetDatauserbusinesstextSparseResponses,
  GetDatauserintegerData,
  GetDatauserintegerErrors,
  GetDatauserintegerResponses,
  GetDishRecData,
  GetDishRecErrors,
  GetDishRecResponses,
  GetFeedAlertData,
  GetFeedAlertErrors,
  GetFeedAlertResponses,
  GetFeedItemDataData,
  GetFeedItemDataErrors,
  GetFeedItemDataResponses,
  GetFilterConfigsData,
  GetFilterConfigsErrors,
  GetFilterConfigsResponses,
  GetFollowCountFollowersData,
  GetFollowCountFollowersErrors,
  GetFollowCountFollowersResponses,
  GetFollowCountFollowingData,
  GetFollowCountFollowingErrors,
  GetFollowCountFollowingResponses,
  GetFollowData,
  GetFollowErrors,
  GetFollowersData,
  GetFollowersErrors,
  GetFollowersResponses,
  GetFollowingData,
  GetFollowingErrors,
  GetFollowingResponses,
  GetFollowRequestsData,
  GetFollowRequestsErrors,
  GetFollowRequestsResponses,
  GetFollowResponses,
  GetFriendsBookmarkedData,
  GetFriendsBookmarkedErrors,
  GetFriendsBookmarkedResponses,
  GetGlassfyConfigData,
  GetGlassfyConfigErrors,
  GetGlassfyConfigResponses,
  GetHasContactsData,
  GetHasContactsErrors,
  GetHasContactsResponses,
  GetInvitesFeatureProgressData,
  GetInvitesFeatureProgressErrors,
  GetInvitesFeatureProgressResponses,
  GetInvitesRemainingData,
  GetInvitesRemainingErrors,
  GetInvitesRemainingResponses,
  GetLeaderboardData,
  GetLeaderboardErrors,
  GetLeaderboardResponses,
  GetLoggedInData,
  GetLoggedInErrors,
  GetLoggedInResponses,
  GetMarkReadData,
  GetMarkReadErrors,
  GetMarkReadResponses,
  GetMutedData,
  GetMutedErrors,
  GetMutedResponses,
  GetMutualBookmarksData,
  GetMutualBookmarksErrors,
  GetMutualBookmarksResponses,
  GetMyFeaturedListChallengesData,
  GetMyFeaturedListChallengesErrors,
  GetMyFeaturedListChallengesResponses,
  GetNewsfeedCurrentData,
  GetNewsfeedCurrentErrors,
  GetNewsfeedCurrentResponses,
  GetNewsfeedDataData,
  GetNewsfeedDataErrors,
  GetNewsfeedDataResponses,
  GetNewsfeedReactionData,
  GetNewsfeedReactionErrors,
  GetNewsfeedReactionResponses,
  GetNewsfeedUserData,
  GetNewsfeedUserErrors,
  GetNewsfeedUserResponses,
  GetNotificationCommentCountData,
  GetNotificationCommentCountErrors,
  GetNotificationCommentCountResponses,
  GetNotificationReactionData,
  GetNotificationReactionErrors,
  GetNotificationReactionResponses,
  GetNumberParamsBeforeUserData,
  GetNumberParamsBeforeUserErrors,
  GetNumberParamsBeforeUserResponses,
  GetNumberParamsData,
  GetNumberParamsErrors,
  GetNumberParamsResponses,
  GetPeopleYouMayKnowFullData,
  GetPeopleYouMayKnowFullErrors,
  GetPeopleYouMayKnowFullResponses,
  GetPlaylistsData,
  GetPlaylistsErrors,
  GetPlaylistsResponses,
  GetPopularInCityData,
  GetPopularInCityErrors,
  GetPopularInCityResponses,
  GetPopupData,
  GetPopupErrors,
  GetPopupResponses,
  GetProfileNewsfeedDataData,
  GetProfileNewsfeedDataErrors,
  GetProfileNewsfeedDataResponses,
  GetProfileProgressData,
  GetProfileProgressErrors,
  GetProfileProgressResponses,
  GetPublishedListByUserData,
  GetPublishedListByUserErrors,
  GetPublishedListByUserResponses,
  GetPublishedListCitiesData,
  GetPublishedListCitiesErrors,
  GetPublishedListCitiesResponses,
  GetPublishedListData,
  GetPublishedListErrors,
  GetPublishedListItemNewData,
  GetPublishedListItemNewErrors,
  GetPublishedListItemNewResponses,
  GetPublishedListResponses,
  GetRankingData,
  GetRankingErrors,
  GetRankingResponses,
  GetRecScoreData,
  GetRecScoreErrors,
  GetRecScoreResponses,
  GetReservationPostingData,
  GetReservationPostingErrors,
  GetReservationPostingResponses,
  GetReservationsClaimedTodayData,
  GetReservationsClaimedTodayErrors,
  GetReservationsClaimedTodayResponses,
  GetResPriorityDataData,
  GetResPriorityDataErrors,
  GetResPriorityDataResponses,
  GetResReportIssueOptionsData,
  GetResReportIssueOptionsErrors,
  GetResReportIssueOptionsResponses,
  GetScoreAverageData,
  GetScoreAverageErrors,
  GetScoreAverageResponses,
  GetScoresData,
  GetScoresErrors,
  GetScoresResponses,
  GetSharedMealsData,
  GetSharedMealsErrors,
  GetSharedMealsResponses,
  GetSharesheetConfigData,
  GetSharesheetConfigErrors,
  GetSharesheetConfigResponses,
  GetShortListData,
  GetShortListErrors,
  GetShortListResponses,
  GetSingleNotificationDataData,
  GetSingleNotificationDataErrors,
  GetSingleNotificationDataResponses,
  GetStaticMapsUrlData,
  GetStaticMapsUrlErrors,
  GetStaticMapsUrlResponses,
  GetStripePaymentMethodsData,
  GetStripePaymentMethodsErrors,
  GetStripePaymentMethodsResponses,
  GetSuggestBusinessCuisineData,
  GetSuggestBusinessCuisineErrors,
  GetSuggestBusinessCuisineResponses,
  GetSuggestBusinessPriceData,
  GetSuggestBusinessPriceErrors,
  GetSuggestBusinessPriceResponses,
  GetTaggedUsersData,
  GetTaggedUsersErrors,
  GetTaggedUsersOnBusinessData,
  GetTaggedUsersOnBusinessErrors,
  GetTaggedUsersOnBusinessResponses,
  GetTaggedUsersResponses,
  GetTasteProfileConfigData,
  GetTasteProfileConfigErrors,
  GetTasteProfileConfigResponses,
  GetTextParamsBeforeUserData,
  GetTextParamsBeforeUserErrors,
  GetTextParamsBeforeUserResponses,
  GetTextParamsData,
  GetTextParamsErrors,
  GetTextParamsResponses,
  GetTopCitiesData,
  GetTopCitiesErrors,
  GetTopCitiesResponses,
  GetTrendingData,
  GetTrendingErrors,
  GetTrendingResponses,
  GetTriggerData,
  GetTriggerErrors,
  GetTriggerResponses,
  GetUserActivitySubscriptionsData,
  GetUserActivitySubscriptionsErrors,
  GetUserActivitySubscriptionsResponses,
  GetUserBioData,
  GetUserBioErrors,
  GetUserBioResponses,
  GetUserBusinessLabelsData,
  GetUserBusinessLabelsErrors,
  GetUserBusinessLabelsResponses,
  GetUserBusinessPhotoData,
  GetUserBusinessPhotoErrors,
  GetUserBusinessPhotoResponses,
  GetUserBusinessPhotosData,
  GetUserBusinessPhotosErrors,
  GetUserBusinessPhotosResponses,
  GetUserFieldCountBookmarkedData,
  GetUserFieldCountBookmarkedErrors,
  GetUserFieldCountBookmarkedResponses,
  GetUserFieldCountRankData,
  GetUserFieldCountRankErrors,
  GetUserFieldCountRankResponses,
  GetUserGuideData,
  GetUserGuideErrors,
  GetUserGuideItemsCloseData,
  GetUserGuideItemsCloseErrors,
  GetUserGuideItemsCloseResponses,
  GetUserGuideItemsData,
  GetUserGuideItemsErrors,
  GetUserGuideItemsResponses,
  GetUserGuideResponses,
  GetUserMemberData,
  GetUserMemberErrors,
  GetUserMemberResponses,
  GetUserScoresCachedData,
  GetUserScoresCachedErrors,
  GetUserScoresCachedResponses,
  GetUserScoresData,
  GetUserScoresErrors,
  GetUserScoresResponses,
  GetUserSearchData,
  GetUserSearchErrors,
  GetUserSearchResponses,
  GetUserSettingData,
  GetUserSettingErrors,
  GetUserSettingResponses,
  GetUserStreakData,
  GetUserStreakErrors,
  GetUserStreakResponses,
  GetUserTagSuggestionsData,
  GetUserTagSuggestionsErrors,
  GetUserTagSuggestionsResponses,
  GetVisitDatesOnBusinessData,
  GetVisitDatesOnBusinessErrors,
  GetVisitDatesOnBusinessResponses,
  GetYourNewsfeedDataData,
  GetYourNewsfeedDataErrors,
  GetYourNewsfeedDataResponses,
  GetYourNewsfeedReactionData,
  GetYourNewsfeedReactionErrors,
  GetYourNewsfeedReactionResponses,
  LoginData,
  LoginErrors,
  LoginResponses,
  ProcessAddRankingData,
  ProcessAddRankingErrors,
  ProcessAddRankingResponses,
  RefreshTokenData,
  RefreshTokenResponses,
  RemoveBookmarkData,
  RemoveBookmarkErrors,
  RemoveBookmarkResponses,
  SearchAppData,
  SearchAppErrors,
  SearchAppResponses,
  UpdateDeviceData,
  UpdateDeviceErrors,
  UpdateDeviceResponses,
  UpdateFollowData,
  UpdateFollowErrors,
  UpdateFollowResponses,
  UpdateNotificationData,
  UpdateNotificationErrors,
  UpdateNotificationResponses,
  UpdateUserData,
  UpdateUserErrors,
  UpdateUserResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Login (email or phone + password) — SimpleJWT
 */
export const login = <ThrowOnError extends boolean = false>(
  options: Options<LoginData, ThrowOnError>,
): RequestResult<LoginResponses, LoginErrors, ThrowOnError> =>
  (options.client ?? client).post<LoginResponses, LoginErrors, ThrowOnError>({
    url: "/api/token/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Refresh an access token — refresh token itself is not rotated
 */
export const refreshToken = <ThrowOnError extends boolean = false>(
  options: Options<RefreshTokenData, ThrowOnError>,
): RequestResult<RefreshTokenResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<RefreshTokenResponses, unknown, ThrowOnError>(
    {
      url: "/api/token/refresh/",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    },
  );

/**
 * Current user's full profile (incl. email, phone_no, home_city, referrer, sessions)
 */
export const getLoggedIn = <ThrowOnError extends boolean = false>(
  options: Options<GetLoggedInData, ThrowOnError>,
): RequestResult<GetLoggedInResponses, GetLoggedInErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetLoggedInResponses,
    GetLoggedInErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/user/logged-in/",
    ...options,
  });

/**
 * Session heartbeat — sync FCM/live-activity tokens & session info; returns full user object
 */
export const updateUser = <ThrowOnError extends boolean = false>(
  options: Options<UpdateUserData, ThrowOnError>,
): RequestResult<UpdateUserResponses, UpdateUserErrors, ThrowOnError> =>
  (options.client ?? client).put<
    UpdateUserResponses,
    UpdateUserErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/user/u/{uuid}/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Update device attribution record (AppsFlyer); request body not captured
 */
export const updateDevice = <ThrowOnError extends boolean = false>(
  options: Options<UpdateDeviceData, ThrowOnError>,
): RequestResult<UpdateDeviceResponses, UpdateDeviceErrors, ThrowOnError> =>
  (options.client ?? client).put<
    UpdateDeviceResponses,
    UpdateDeviceErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/device/{deviceId}/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * App-wide rank for a user
 */
export const getAppRank = <ThrowOnError extends boolean = false>(
  options: Options<GetAppRankData, ThrowOnError>,
): RequestResult<GetAppRankResponses, GetAppRankErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetAppRankResponses,
    GetAppRankErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/app-rank/{uuid}/",
    ...options,
  });

/**
 * Check user settings status
 */
export const getCheckUserSettings = <ThrowOnError extends boolean = false>(
  options: Options<GetCheckUserSettingsData, ThrowOnError>,
): RequestResult<
  GetCheckUserSettingsResponses,
  GetCheckUserSettingsErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetCheckUserSettingsResponses,
    GetCheckUserSettingsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/check-user-settings/",
    ...options,
  });

/**
 * Count of places ranked by the user this year
 */
export const getCountRankedThisYear = <ThrowOnError extends boolean = false>(
  options: Options<GetCountRankedThisYearData, ThrowOnError>,
): RequestResult<
  GetCountRankedThisYearResponses,
  GetCountRankedThisYearErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetCountRankedThisYearResponses,
    GetCountRankedThisYearErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/count-ranked-this-year/{uuid}/",
    ...options,
  });

/**
 * Creator-subscribe status/config
 */
export const getCreatorSubscribe = <ThrowOnError extends boolean = false>(
  options: Options<GetCreatorSubscribeData, ThrowOnError>,
): RequestResult<
  GetCreatorSubscribeResponses,
  GetCreatorSubscribeErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetCreatorSubscribeResponses,
    GetCreatorSubscribeErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/creator-subscribe/",
    ...options,
  });

/**
 * EAV integer-valued user fields (generic field layer, see reference §4)
 */
export const getDatauserinteger = <ThrowOnError extends boolean = false>(
  options: Options<GetDatauserintegerData, ThrowOnError>,
): RequestResult<
  GetDatauserintegerResponses,
  GetDatauserintegerErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetDatauserintegerResponses,
    GetDatauserintegerErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/datauserinteger/",
    ...options,
  });

/**
 * Glassfy (in-app-purchase) config
 */
export const getGlassfyConfig = <ThrowOnError extends boolean = false>(
  options: Options<GetGlassfyConfigData, ThrowOnError>,
): RequestResult<
  GetGlassfyConfigResponses,
  GetGlassfyConfigErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetGlassfyConfigResponses,
    GetGlassfyConfigErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/glassfy-config/",
    ...options,
  });

/**
 * Whether the user has synced device contacts
 */
export const getHasContacts = <ThrowOnError extends boolean = false>(
  options: Options<GetHasContactsData, ThrowOnError>,
): RequestResult<GetHasContactsResponses, GetHasContactsErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetHasContactsResponses,
    GetHasContactsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/has-contacts/{uuid}/",
    ...options,
  });

/**
 * Invites feature progress for the user
 */
export const getInvitesFeatureProgress = <ThrowOnError extends boolean = false>(
  options: Options<GetInvitesFeatureProgressData, ThrowOnError>,
): RequestResult<
  GetInvitesFeatureProgressResponses,
  GetInvitesFeatureProgressErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetInvitesFeatureProgressResponses,
    GetInvitesFeatureProgressErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/invites-feature-progress/{uuid}/",
    ...options,
  });

/**
 * Remaining invites for the user
 */
export const getInvitesRemaining = <ThrowOnError extends boolean = false>(
  options: Options<GetInvitesRemainingData, ThrowOnError>,
): RequestResult<
  GetInvitesRemainingResponses,
  GetInvitesRemainingErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetInvitesRemainingResponses,
    GetInvitesRemainingErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/invites-remaining/{uuid}/",
    ...options,
  });

/**
 * EAV numeric field definitions available before user context (see reference §4)
 */
export const getNumberParamsBeforeUser = <ThrowOnError extends boolean = false>(
  options: Options<GetNumberParamsBeforeUserData, ThrowOnError>,
): RequestResult<
  GetNumberParamsBeforeUserResponses,
  GetNumberParamsBeforeUserErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetNumberParamsBeforeUserResponses,
    GetNumberParamsBeforeUserErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/number-params-before-user/",
    ...options,
  });

/**
 * EAV numeric field values for a user (see reference §4)
 */
export const getNumberParams = <ThrowOnError extends boolean = false>(
  options: Options<GetNumberParamsData, ThrowOnError>,
): RequestResult<
  GetNumberParamsResponses,
  GetNumberParamsErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetNumberParamsResponses,
    GetNumberParamsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/number-params/{uuid}/",
    ...options,
  });

/**
 * Onboarding/profile-completion progress for a user
 */
export const getProfileProgress = <ThrowOnError extends boolean = false>(
  options: Options<GetProfileProgressData, ThrowOnError>,
): RequestResult<
  GetProfileProgressResponses,
  GetProfileProgressErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetProfileProgressResponses,
    GetProfileProgressErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/profile-progress/{uuid}/",
    ...options,
  });

/**
 * Native share-sheet config
 */
export const getSharesheetConfig = <ThrowOnError extends boolean = false>(
  options: Options<GetSharesheetConfigData, ThrowOnError>,
): RequestResult<
  GetSharesheetConfigResponses,
  GetSharesheetConfigErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetSharesheetConfigResponses,
    GetSharesheetConfigErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/sharesheet-config/",
    ...options,
  });

/**
 * Taste-profile config for a user
 */
export const getTasteProfileConfig = <ThrowOnError extends boolean = false>(
  options: Options<GetTasteProfileConfigData, ThrowOnError>,
): RequestResult<
  GetTasteProfileConfigResponses,
  GetTasteProfileConfigErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetTasteProfileConfigResponses,
    GetTasteProfileConfigErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/taste-profile-config/{uuid}/",
    ...options,
  });

/**
 * EAV text field definitions available before user context (see reference §4)
 */
export const getTextParamsBeforeUser = <ThrowOnError extends boolean = false>(
  options: Options<GetTextParamsBeforeUserData, ThrowOnError>,
): RequestResult<
  GetTextParamsBeforeUserResponses,
  GetTextParamsBeforeUserErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetTextParamsBeforeUserResponses,
    GetTextParamsBeforeUserErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/text-params-before-user/",
    ...options,
  });

/**
 * EAV text field values for a user (see reference §4)
 */
export const getTextParams = <ThrowOnError extends boolean = false>(
  options: Options<GetTextParamsData, ThrowOnError>,
): RequestResult<GetTextParamsResponses, GetTextParamsErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetTextParamsResponses,
    GetTextParamsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/text-params/{uuid}/",
    ...options,
  });

/**
 * In-app nudge/trigger config
 */
export const getTrigger = <ThrowOnError extends boolean = false>(
  options: Options<GetTriggerData, ThrowOnError>,
): RequestResult<GetTriggerResponses, GetTriggerErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetTriggerResponses,
    GetTriggerErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/trigger/",
    ...options,
  });

/**
 * Read user settings (EAV read)
 */
export const getUserSetting = <ThrowOnError extends boolean = false>(
  options: Options<GetUserSettingData, ThrowOnError>,
): RequestResult<GetUserSettingResponses, GetUserSettingErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetUserSettingResponses,
    GetUserSettingErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/user-setting/",
    ...options,
  });

/**
 * Write a user setting (EAV write) — `POST {user, field_name, value}`
 */
export const createUserSetting = <ThrowOnError extends boolean = false>(
  options: Options<CreateUserSettingData, ThrowOnError>,
): RequestResult<
  CreateUserSettingResponses,
  CreateUserSettingErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateUserSettingResponses,
    CreateUserSettingErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/user-setting/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * A user's bio text
 */
export const getUserBio = <ThrowOnError extends boolean = false>(
  options: Options<GetUserBioData, ThrowOnError>,
): RequestResult<GetUserBioResponses, GetUserBioErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetUserBioResponses,
    GetUserBioErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/user/bio/",
    ...options,
  });

/**
 * Membership/account info for a user
 */
export const getUserMember = <ThrowOnError extends boolean = false>(
  options: Options<GetUserMemberData, ThrowOnError>,
): RequestResult<GetUserMemberResponses, GetUserMemberErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetUserMemberResponses,
    GetUserMemberErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/user/member/",
    ...options,
  });

/**
 * A user's ranking streak
 */
export const getUserStreak = <ThrowOnError extends boolean = false>(
  options: Options<GetUserStreakData, ThrowOnError>,
): RequestResult<GetUserStreakResponses, GetUserStreakErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetUserStreakResponses,
    GetUserStreakErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/user/streak/",
    ...options,
  });

/**
 * All cities Beli operates in (returned whole; no pagination observed)
 */
export const getAllCities = <ThrowOnError extends boolean = false>(
  options: Options<GetAllCitiesData, ThrowOnError>,
): RequestResult<GetAllCitiesResponses, GetAllCitiesErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetAllCitiesResponses,
    GetAllCitiesErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/all-cities/",
    ...options,
  });

/**
 * Resolve/build a shareable link for a business
 */
export const getBusinessLink = <ThrowOnError extends boolean = false>(
  options: Options<GetBusinessLinkData, ThrowOnError>,
): RequestResult<
  GetBusinessLinkResponses,
  GetBusinessLinkErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetBusinessLinkResponses,
    GetBusinessLinkErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/business-link/",
    ...options,
  });

/**
 * Look up (get-or-create) a business by internal id or Google place_id
 */
export const getBusiness = <ThrowOnError extends boolean = false>(
  options: Options<GetBusinessData, ThrowOnError>,
): RequestResult<GetBusinessResponses, GetBusinessErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetBusinessResponses,
    GetBusinessErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/business/",
    ...options,
  });

/**
 * All cuisine tags known to the system
 */
export const getCuisineAllCuisines = <ThrowOnError extends boolean = false>(
  options: Options<GetCuisineAllCuisinesData, ThrowOnError>,
): RequestResult<
  GetCuisineAllCuisinesResponses,
  GetCuisineAllCuisinesErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetCuisineAllCuisinesResponses,
    GetCuisineAllCuisinesErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/cuisine/all-cuisines/",
    ...options,
  });

/**
 * Resolve the current city for a user from device coordinates
 */
export const getCurrentCity = <ThrowOnError extends boolean = false>(
  options: Options<GetCurrentCityData, ThrowOnError>,
): RequestResult<GetCurrentCityResponses, GetCurrentCityErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetCurrentCityResponses,
    GetCurrentCityErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/current-city/{uuid}/{coords}/",
    ...options,
  });

/**
 * Available search/filter configuration (facets)
 */
export const getFilterConfigs = <ThrowOnError extends boolean = false>(
  options: Options<GetFilterConfigsData, ThrowOnError>,
): RequestResult<
  GetFilterConfigsResponses,
  GetFilterConfigsErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetFilterConfigsResponses,
    GetFilterConfigsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/filter-configs/",
    ...options,
  });

/**
 * Filtered/trending business discovery query (list results)
 */
export const createFilterList = <ThrowOnError extends boolean = false>(
  options: Options<CreateFilterListData, ThrowOnError>,
): RequestResult<
  CreateFilterListResponses,
  CreateFilterListErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateFilterListResponses,
    CreateFilterListErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/filter-list/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Available filter option values for the discovery query builder; body shape not fully captured
 */
export const createFilterOptions = <ThrowOnError extends boolean = false>(
  options: Options<CreateFilterOptionsData, ThrowOnError>,
): RequestResult<
  CreateFilterOptionsResponses,
  CreateFilterOptionsErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateFilterOptionsResponses,
    CreateFilterOptionsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/filter-options/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Popular businesses in a given city
 */
export const getPopularInCity = <ThrowOnError extends boolean = false>(
  options: Options<GetPopularInCityData, ThrowOnError>,
): RequestResult<
  GetPopularInCityResponses,
  GetPopularInCityErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetPopularInCityResponses,
    GetPopularInCityErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/popular-in-city/{uuid}/{city}/",
    ...options,
  });

/**
 * Cities that have published lists/guides
 */
export const getPublishedListCities = <ThrowOnError extends boolean = false>(
  options: Options<GetPublishedListCitiesData, ThrowOnError>,
): RequestResult<
  GetPublishedListCitiesResponses,
  GetPublishedListCitiesErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetPublishedListCitiesResponses,
    GetPublishedListCitiesErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/published-list-cities/",
    ...options,
  });

/**
 * Primary in-app search (businesses, users, lists)
 */
export const searchApp = <ThrowOnError extends boolean = false>(
  options: Options<SearchAppData, ThrowOnError>,
): RequestResult<SearchAppResponses, SearchAppErrors, ThrowOnError> =>
  (options.client ?? client).get<
    SearchAppResponses,
    SearchAppErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/search-app/",
    ...options,
  });

/**
 * Top/featured cities
 */
export const getTopCities = <ThrowOnError extends boolean = false>(
  options: Options<GetTopCitiesData, ThrowOnError>,
): RequestResult<GetTopCitiesResponses, GetTopCitiesErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetTopCitiesResponses,
    GetTopCitiesErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/top-cities/",
    ...options,
  });

/**
 * Trending businesses for a user
 */
export const getTrending = <ThrowOnError extends boolean = false>(
  options: Options<GetTrendingData, ThrowOnError>,
): RequestResult<GetTrendingResponses, GetTrendingErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetTrendingResponses,
    GetTrendingErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/trending/{uuid}/",
    ...options,
  });

/**
 * Whether a user has bookmarked a business
 */
export const getBookmarkStatus = <ThrowOnError extends boolean = false>(
  options: Options<GetBookmarkStatusData, ThrowOnError>,
): RequestResult<
  GetBookmarkStatusResponses,
  GetBookmarkStatusErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetBookmarkStatusResponses,
    GetBookmarkStatusErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/bookmark-status/{uuid}/{id}/",
    ...options,
  });

/**
 * Count of users who have rated a business
 */
export const getBusinessCountRated = <ThrowOnError extends boolean = false>(
  options: Options<GetBusinessCountRatedData, ThrowOnError>,
): RequestResult<
  GetBusinessCountRatedResponses,
  GetBusinessCountRatedErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetBusinessCountRatedResponses,
    GetBusinessCountRatedErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/business-count-rated/{id}/",
    ...options,
  });

/**
 * Friend-activity summary text for a business
 */
export const getBusinessFriendText = <ThrowOnError extends boolean = false>(
  options: Options<GetBusinessFriendTextData, ThrowOnError>,
): RequestResult<
  GetBusinessFriendTextResponses,
  GetBusinessFriendTextErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetBusinessFriendTextResponses,
    GetBusinessFriendTextErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/business-friend-text/{uuid}/{id}/",
    ...options,
  });

/**
 * Score-distribution histogram data for a business
 */
export const getBusinessHistogramData = <ThrowOnError extends boolean = false>(
  options: Options<GetBusinessHistogramDataData, ThrowOnError>,
): RequestResult<
  GetBusinessHistogramDataResponses,
  GetBusinessHistogramDataErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetBusinessHistogramDataResponses,
    GetBusinessHistogramDataErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/business-histogram-data/{id}/",
    ...options,
  });

/**
 * Available business label/distinction types
 */
export const getBusinessLabels = <ThrowOnError extends boolean = false>(
  options: Options<GetBusinessLabelsData, ThrowOnError>,
): RequestResult<
  GetBusinessLabelsResponses,
  GetBusinessLabelsErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetBusinessLabelsResponses,
    GetBusinessLabelsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/business-labels/",
    ...options,
  });

/**
 * EAV boolean-valued user-business field(s) for closed/resolved state (see reference §4)
 */
export const getClosedatauserbusinessboolean = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetClosedatauserbusinessbooleanData, ThrowOnError>,
): RequestResult<
  GetClosedatauserbusinessbooleanResponses,
  GetClosedatauserbusinessbooleanErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetClosedatauserbusinessbooleanResponses,
    GetClosedatauserbusinessbooleanErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/closedatauserbusinessboolean/",
    ...options,
  });

/**
 * Count of user-business occasion tags for a business
 */
export const getCountuserbusinessoccasion = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetCountuserbusinessoccasionData, ThrowOnError>,
): RequestResult<
  GetCountuserbusinessoccasionResponses,
  GetCountuserbusinessoccasionErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetCountuserbusinessoccasionResponses,
    GetCountuserbusinessoccasionErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/countuserbusinessoccasion/{id}/",
    ...options,
  });

/**
 * EAV float-valued business fields, sparse layer (see reference §4)
 */
export const getDatabusinessfloatSparse = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetDatabusinessfloatSparseData, ThrowOnError>,
): RequestResult<
  GetDatabusinessfloatSparseResponses,
  GetDatabusinessfloatSparseErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetDatabusinessfloatSparseResponses,
    GetDatabusinessfloatSparseErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/databusinessfloat-sparse/",
    ...options,
  });

/**
 * EAV text-valued user-business fields, sparse layer (see reference §4)
 */
export const getDatauserbusinesstextSparse = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetDatauserbusinesstextSparseData, ThrowOnError>,
): RequestResult<
  GetDatauserbusinesstextSparseResponses,
  GetDatauserbusinesstextSparseErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetDatauserbusinesstextSparseResponses,
    GetDatauserbusinesstextSparseErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/datauserbusinesstext-sparse/",
    ...options,
  });

/**
 * Recommended dishes for a business
 */
export const getDishRec = <ThrowOnError extends boolean = false>(
  options: Options<GetDishRecData, ThrowOnError>,
): RequestResult<GetDishRecResponses, GetDishRecErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetDishRecResponses,
    GetDishRecErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/dish-rec/",
    ...options,
  });

/**
 * Friends who have bookmarked a business
 */
export const getFriendsBookmarked = <ThrowOnError extends boolean = false>(
  options: Options<GetFriendsBookmarkedData, ThrowOnError>,
): RequestResult<
  GetFriendsBookmarkedResponses,
  GetFriendsBookmarkedErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetFriendsBookmarkedResponses,
    GetFriendsBookmarkedErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/friends-bookmarked/{uuid}/{id}/",
    ...options,
  });

/**
 * Recommendation score for a business
 */
export const getRecScore = <ThrowOnError extends boolean = false>(
  options: Options<GetRecScoreData, ThrowOnError>,
): RequestResult<GetRecScoreResponses, GetRecScoreErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetRecScoreResponses,
    GetRecScoreErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/rec-score/",
    ...options,
  });

/**
 * Friend scores for a user (reference §5: query filters are ignored server-side — fetch once and client-filter by business_id)
 *
 */
export const getScores = <ThrowOnError extends boolean = false>(
  options: Options<GetScoresData, ThrowOnError>,
): RequestResult<GetScoresResponses, GetScoresErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetScoresResponses,
    GetScoresErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/scores/{uuid}/{id}/",
    ...options,
  });

/**
 * Static map image URL for a business location
 */
export const getStaticMapsUrl = <ThrowOnError extends boolean = false>(
  options: Options<GetStaticMapsUrlData, ThrowOnError>,
): RequestResult<
  GetStaticMapsUrlResponses,
  GetStaticMapsUrlErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetStaticMapsUrlResponses,
    GetStaticMapsUrlErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/static-maps-url/",
    ...options,
  });

/**
 * Suggested cuisine tags for a business
 */
export const getSuggestBusinessCuisine = <ThrowOnError extends boolean = false>(
  options: Options<GetSuggestBusinessCuisineData, ThrowOnError>,
): RequestResult<
  GetSuggestBusinessCuisineResponses,
  GetSuggestBusinessCuisineErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetSuggestBusinessCuisineResponses,
    GetSuggestBusinessCuisineErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/suggest-business-cuisine/",
    ...options,
  });

/**
 * Suggested price tier for a business
 */
export const getSuggestBusinessPrice = <ThrowOnError extends boolean = false>(
  options: Options<GetSuggestBusinessPriceData, ThrowOnError>,
): RequestResult<
  GetSuggestBusinessPriceResponses,
  GetSuggestBusinessPriceErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetSuggestBusinessPriceResponses,
    GetSuggestBusinessPriceErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/suggest-business-price/",
    ...options,
  });

/**
 * Users tagged in reviews of a business
 */
export const getTaggedUsersOnBusiness = <ThrowOnError extends boolean = false>(
  options: Options<GetTaggedUsersOnBusinessData, ThrowOnError>,
): RequestResult<
  GetTaggedUsersOnBusinessResponses,
  GetTaggedUsersOnBusinessErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetTaggedUsersOnBusinessResponses,
    GetTaggedUsersOnBusinessErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/tagged-users-on-business/{uuid}/{id}/",
    ...options,
  });

/**
 * A user's labels/distinctions applied to businesses
 */
export const getUserBusinessLabels = <ThrowOnError extends boolean = false>(
  options: Options<GetUserBusinessLabelsData, ThrowOnError>,
): RequestResult<
  GetUserBusinessLabelsResponses,
  GetUserBusinessLabelsErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetUserBusinessLabelsResponses,
    GetUserBusinessLabelsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/user-business-labels/",
    ...options,
  });

/**
 * A single user-business photo record (get-or-create semantics per Allow header)
 */
export const getUserBusinessPhoto = <ThrowOnError extends boolean = false>(
  options: Options<GetUserBusinessPhotoData, ThrowOnError>,
): RequestResult<
  GetUserBusinessPhotoResponses,
  GetUserBusinessPhotoErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetUserBusinessPhotoResponses,
    GetUserBusinessPhotoErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/user-business-photo/",
    ...options,
  });

/**
 * All photos for a user across businesses (returned whole; no pagination observed per reference §5)
 */
export const getUserBusinessPhotos = <ThrowOnError extends boolean = false>(
  options: Options<GetUserBusinessPhotosData, ThrowOnError>,
): RequestResult<
  GetUserBusinessPhotosResponses,
  GetUserBusinessPhotosErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetUserBusinessPhotosResponses,
    GetUserBusinessPhotosErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/user-business-photos/",
    ...options,
  });

/**
 * Dates a user visited a business
 */
export const getVisitDatesOnBusiness = <ThrowOnError extends boolean = false>(
  options: Options<GetVisitDatesOnBusinessData, ThrowOnError>,
): RequestResult<
  GetVisitDatesOnBusinessResponses,
  GetVisitDatesOnBusinessErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetVisitDatesOnBusinessResponses,
    GetVisitDatesOnBusinessErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/visit-dates-on-business/{uuid}/{id}/",
    ...options,
  });

/**
 * Correlation/affinity data between two users
 */
export const getCorr = <ThrowOnError extends boolean = false>(
  options: Options<GetCorrData, ThrowOnError>,
): RequestResult<GetCorrResponses, GetCorrErrors, ThrowOnError> =>
  (options.client ?? client).get<GetCorrResponses, GetCorrErrors, ThrowOnError>(
    {
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/corr/{uuid1}/{uuid2}/",
      ...options,
    },
  );

/**
 * Follower count for a user (bare integer per reference §8 FollowCount)
 */
export const getFollowCountFollowers = <ThrowOnError extends boolean = false>(
  options: Options<GetFollowCountFollowersData, ThrowOnError>,
): RequestResult<
  GetFollowCountFollowersResponses,
  GetFollowCountFollowersErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetFollowCountFollowersResponses,
    GetFollowCountFollowersErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/follow-count/{uuid}/followers/",
    ...options,
  });

/**
 * Following count for a user (bare integer per reference §8 FollowCount)
 */
export const getFollowCountFollowing = <ThrowOnError extends boolean = false>(
  options: Options<GetFollowCountFollowingData, ThrowOnError>,
): RequestResult<
  GetFollowCountFollowingResponses,
  GetFollowCountFollowingErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetFollowCountFollowingResponses,
    GetFollowCountFollowingErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/follow-count/{uuid}/following/",
    ...options,
  });

/**
 * Pending follow requests for a user
 */
export const getFollowRequests = <ThrowOnError extends boolean = false>(
  options: Options<GetFollowRequestsData, ThrowOnError>,
): RequestResult<
  GetFollowRequestsResponses,
  GetFollowRequestsErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetFollowRequestsResponses,
    GetFollowRequestsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/follow-requests/{uuid}/",
    ...options,
  });

/**
 * Existing-edge check between a follower and followed user
 */
export const getFollow = <ThrowOnError extends boolean = false>(
  options: Options<GetFollowData, ThrowOnError>,
): RequestResult<GetFollowResponses, GetFollowErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetFollowResponses,
    GetFollowErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/follow/",
    ...options,
  });

/**
 * Follow a user
 */
export const createFollow = <ThrowOnError extends boolean = false>(
  options: Options<CreateFollowData, ThrowOnError>,
): RequestResult<CreateFollowResponses, CreateFollowErrors, ThrowOnError> =>
  (options.client ?? client).post<
    CreateFollowResponses,
    CreateFollowErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/follow/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Unfollow (set unfollow_dt on a follow edge)
 */
export const updateFollow = <ThrowOnError extends boolean = false>(
  options: Options<UpdateFollowData, ThrowOnError>,
): RequestResult<UpdateFollowResponses, UpdateFollowErrors, ThrowOnError> =>
  (options.client ?? client).put<
    UpdateFollowResponses,
    UpdateFollowErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/follow/{id}/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * A user's followers (reference §2: known to intermittently 503 — treat as best-effort)
 *
 */
export const getFollowers = <ThrowOnError extends boolean = false>(
  options: Options<GetFollowersData, ThrowOnError>,
): RequestResult<GetFollowersResponses, GetFollowersErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetFollowersResponses,
    GetFollowersErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/followers/{uuid}/",
    ...options,
  });

/**
 * Users a user is following
 */
export const getFollowing = <ThrowOnError extends boolean = false>(
  options: Options<GetFollowingData, ThrowOnError>,
): RequestResult<GetFollowingResponses, GetFollowingErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetFollowingResponses,
    GetFollowingErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/following/{uuid}/",
    ...options,
  });

/**
 * Suggested users to tag (e.g. when writing a review)
 */
export const getUserTagSuggestions = <ThrowOnError extends boolean = false>(
  options: Options<GetUserTagSuggestionsData, ThrowOnError>,
): RequestResult<
  GetUserTagSuggestionsResponses,
  GetUserTagSuggestionsErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetUserTagSuggestionsResponses,
    GetUserTagSuggestionsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/get-user-tag-suggestions/",
    ...options,
  });

/**
 * RANK leaderboard among all members for a user
 */
export const getLeaderboard = <ThrowOnError extends boolean = false>(
  options: Options<GetLeaderboardData, ThrowOnError>,
): RequestResult<GetLeaderboardResponses, GetLeaderboardErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetLeaderboardResponses,
    GetLeaderboardErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/leaderboard/{uuid}/RANK/all_members/",
    ...options,
  });

/**
 * Businesses bookmarked by both users (comma-joined path segment per reference §7)
 */
export const getMutualBookmarks = <ThrowOnError extends boolean = false>(
  options: Options<GetMutualBookmarksData, ThrowOnError>,
): RequestResult<
  GetMutualBookmarksResponses,
  GetMutualBookmarksErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetMutualBookmarksResponses,
    GetMutualBookmarksErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/mutual-bookmarks/{uuid1},{uuid2}/",
    ...options,
  });

/**
 * Batch affinity/correlation lookup for a list of users
 */
export const createPassedUserCorr = <ThrowOnError extends boolean = false>(
  options: Options<CreatePassedUserCorrData, ThrowOnError>,
): RequestResult<
  CreatePassedUserCorrResponses,
  CreatePassedUserCorrErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreatePassedUserCorrResponses,
    CreatePassedUserCorrErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/passed-user-corr/{uuid}/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Full "people you may know" suggestions for a user
 */
export const getPeopleYouMayKnowFull = <ThrowOnError extends boolean = false>(
  options: Options<GetPeopleYouMayKnowFullData, ThrowOnError>,
): RequestResult<
  GetPeopleYouMayKnowFullResponses,
  GetPeopleYouMayKnowFullErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetPeopleYouMayKnowFullResponses,
    GetPeopleYouMayKnowFullErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/people-you-may-know-full/{uuid}/",
    ...options,
  });

/**
 * Meals/businesses shared between two users
 */
export const getSharedMeals = <ThrowOnError extends boolean = false>(
  options: Options<GetSharedMealsData, ThrowOnError>,
): RequestResult<GetSharedMealsResponses, GetSharedMealsErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetSharedMealsResponses,
    GetSharedMealsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/shared-meals/{uuid1}/{uuid2}/",
    ...options,
  });

/**
 * Users tagged (generic, not scoped to a business)
 */
export const getTaggedUsers = <ThrowOnError extends boolean = false>(
  options: Options<GetTaggedUsersData, ThrowOnError>,
): RequestResult<GetTaggedUsersResponses, GetTaggedUsersErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetTaggedUsersResponses,
    GetTaggedUsersErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/tagged-users/",
    ...options,
  });

/**
 * Activity-subscription state between two users
 */
export const getUserActivitySubscriptions = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetUserActivitySubscriptionsData, ThrowOnError>,
): RequestResult<
  GetUserActivitySubscriptionsResponses,
  GetUserActivitySubscriptionsErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetUserActivitySubscriptionsResponses,
    GetUserActivitySubscriptionsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/user-activity-subscriptions/{uuid1}/{uuid2}/",
    ...options,
  });

/**
 * Batch user hydration — resolve a list of user ids to full user objects
 */
export const createUserList = <ThrowOnError extends boolean = false>(
  options: Options<CreateUserListData, ThrowOnError>,
): RequestResult<CreateUserListResponses, CreateUserListErrors, ThrowOnError> =>
  (options.client ?? client).post<
    CreateUserListResponses,
    CreateUserListErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/user/list/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Search for users by query string, scoped to a requesting user
 */
export const getUserSearch = <ThrowOnError extends boolean = false>(
  options: Options<GetUserSearchData, ThrowOnError>,
): RequestResult<GetUserSearchResponses, GetUserSearchErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetUserSearchResponses,
    GetUserSearchErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/user/search/{uuid}/{query}/",
    ...options,
  });

/**
 * Create a rating/review (sentiment seed; Beli computes the displayed 0–10 score server-side)
 */
export const createRanking = <ThrowOnError extends boolean = false>(
  options: Options<CreateRankingData, ThrowOnError>,
): RequestResult<CreateRankingResponses, CreateRankingErrors, ThrowOnError> =>
  (options.client ?? client).post<
    CreateRankingResponses,
    CreateRankingErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/add-ranking/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Third step of the rating-create sequence — post-rank share popups (value:null + share flags)
 */
export const checkSharePostRank = <ThrowOnError extends boolean = false>(
  options: Options<CheckSharePostRankData, ThrowOnError>,
): RequestResult<
  CheckSharePostRankResponses,
  CheckSharePostRankErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CheckSharePostRankResponses,
    CheckSharePostRankErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/check-share-post-rank/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Soft-delete a rating/review (PUT with empty body)
 */
export const deleteRanking = <ThrowOnError extends boolean = false>(
  options: Options<DeleteRankingData, ThrowOnError>,
): RequestResult<DeleteRankingResponses, DeleteRankingErrors, ThrowOnError> =>
  (options.client ?? client).put<
    DeleteRankingResponses,
    DeleteRankingErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/delete-ranking/{uuid}/{id}/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * A user's bookmarks
 */
export const getBookmark = <ThrowOnError extends boolean = false>(
  options: Options<GetBookmarkData, ThrowOnError>,
): RequestResult<GetBookmarkResponses, GetBookmarkErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetBookmarkResponses,
    GetBookmarkErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/get-bookmark/",
    ...options,
  });

/**
 * A user's rankings for a category (reference §5: requires user+category, ignores business)
 *
 */
export const getRanking = <ThrowOnError extends boolean = false>(
  options: Options<GetRankingData, ThrowOnError>,
): RequestResult<GetRankingResponses, GetRankingErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetRankingResponses,
    GetRankingErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/get-ranking/",
    ...options,
  });

/**
 * Second step of the rating-create sequence — side effects (clear_playlists, unlocked_playlist_access)
 */
export const processAddRanking = <ThrowOnError extends boolean = false>(
  options: Options<ProcessAddRankingData, ThrowOnError>,
): RequestResult<
  ProcessAddRankingResponses,
  ProcessAddRankingErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    ProcessAddRankingResponses,
    ProcessAddRankingErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/process-add-ranking/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Average score across all categories for a user
 */
export const getScoreAverage = <ThrowOnError extends boolean = false>(
  options: Options<GetScoreAverageData, ThrowOnError>,
): RequestResult<
  GetScoreAverageResponses,
  GetScoreAverageErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetScoreAverageResponses,
    GetScoreAverageErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/score-average/{uuid}/ALL/",
    ...options,
  });

/**
 * Count of a user's bookmarked-field records
 */
export const getUserFieldCountBookmarked = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetUserFieldCountBookmarkedData, ThrowOnError>,
): RequestResult<
  GetUserFieldCountBookmarkedResponses,
  GetUserFieldCountBookmarkedErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetUserFieldCountBookmarkedResponses,
    GetUserFieldCountBookmarkedErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/user-field-count/{uuid}/BOOKMARKED/",
    ...options,
  });

/**
 * Count of a user's RANK-field records
 */
export const getUserFieldCountRank = <ThrowOnError extends boolean = false>(
  options: Options<GetUserFieldCountRankData, ThrowOnError>,
): RequestResult<
  GetUserFieldCountRankResponses,
  GetUserFieldCountRankErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetUserFieldCountRankResponses,
    GetUserFieldCountRankErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/user-field-count/{uuid}/RANK/",
    ...options,
  });

/**
 * Compute/refresh recommendation scores for a user; request body not captured
 */
export const createUserRecScores = <ThrowOnError extends boolean = false>(
  options: Options<CreateUserRecScoresData, ThrowOnError>,
): RequestResult<
  CreateUserRecScoresResponses,
  CreateUserRecScoresErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateUserRecScoresResponses,
    CreateUserRecScoresErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/user-rec-scores/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Cached scores for a user (see reference §8 CachedScore)
 */
export const getUserScoresCached = <ThrowOnError extends boolean = false>(
  options: Options<GetUserScoresCachedData, ThrowOnError>,
): RequestResult<
  GetUserScoresCachedResponses,
  GetUserScoresCachedErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetUserScoresCachedResponses,
    GetUserScoresCachedErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/user-scores-cached/{uuid}/",
    ...options,
  });

/**
 * Scores for a user (see reference §8 Score)
 */
export const getUserScores = <ThrowOnError extends boolean = false>(
  options: Options<GetUserScoresData, ThrowOnError>,
): RequestResult<GetUserScoresResponses, GetUserScoresErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetUserScoresResponses,
    GetUserScoresErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/user-scores/{uuid}/",
    ...options,
  });

/**
 * Write user-business text (e.g. NOTES/review text) via the EAV layer
 */
export const createDataUserBusinessText = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateDataUserBusinessTextData, ThrowOnError>,
): RequestResult<
  CreateDataUserBusinessTextResponses,
  CreateDataUserBusinessTextErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateDataUserBusinessTextResponses,
    CreateDataUserBusinessTextErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/data-user-business-text-new/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Bookmark a business (external source only — beli-mcp; not observed in our captures)
 */
export const createBookmark = <ThrowOnError extends boolean = false>(
  options: Options<CreateBookmarkData, ThrowOnError>,
): RequestResult<CreateBookmarkResponses, CreateBookmarkErrors, ThrowOnError> =>
  (options.client ?? client).post<
    CreateBookmarkResponses,
    CreateBookmarkErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/add-bookmark/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Remove a bookmark from a business (external source only — beli-mcp; not observed in our captures)
 */
export const removeBookmark = <ThrowOnError extends boolean = false>(
  options: Options<RemoveBookmarkData, ThrowOnError>,
): RequestResult<RemoveBookmarkResponses, RemoveBookmarkErrors, ThrowOnError> =>
  (options.client ?? client).put<
    RemoveBookmarkResponses,
    RemoveBookmarkErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/remove-bookmark/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Aggregated "following" activity feed for a user
 */
export const getAggFollowingNew = <ThrowOnError extends boolean = false>(
  options: Options<GetAggFollowingNewData, ThrowOnError>,
): RequestResult<
  GetAggFollowingNewResponses,
  GetAggFollowingNewErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetAggFollowingNewResponses,
    GetAggFollowingNewErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/agg-following-new/{uuid}/",
    ...options,
  });

/**
 * Feed alert/banner state for a user
 */
export const getFeedAlert = <ThrowOnError extends boolean = false>(
  options: Options<GetFeedAlertData, ThrowOnError>,
): RequestResult<GetFeedAlertResponses, GetFeedAlertErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetFeedAlertResponses,
    GetFeedAlertErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/feed-alert/{uuid}/",
    ...options,
  });

/**
 * Feed item data (see reference §8 FeedItem)
 */
export const getFeedItemData = <ThrowOnError extends boolean = false>(
  options: Options<GetFeedItemDataData, ThrowOnError>,
): RequestResult<
  GetFeedItemDataResponses,
  GetFeedItemDataErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetFeedItemDataResponses,
    GetFeedItemDataErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/feed-item-data/",
    ...options,
  });

/**
 * Current newsfeed item for a user by id
 */
export const getNewsfeedCurrent = <ThrowOnError extends boolean = false>(
  options: Options<GetNewsfeedCurrentData, ThrowOnError>,
): RequestResult<
  GetNewsfeedCurrentResponses,
  GetNewsfeedCurrentErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetNewsfeedCurrentResponses,
    GetNewsfeedCurrentErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/newsfeed-current/{uuid}/{id}/",
    ...options,
  });

/**
 * Newsfeed data for a user
 */
export const getNewsfeedData = <ThrowOnError extends boolean = false>(
  options: Options<GetNewsfeedDataData, ThrowOnError>,
): RequestResult<
  GetNewsfeedDataResponses,
  GetNewsfeedDataErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetNewsfeedDataResponses,
    GetNewsfeedDataErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/newsfeed-data/{uuid}/",
    ...options,
  });

/**
 * Reactions on a newsfeed item
 */
export const getNewsfeedReaction = <ThrowOnError extends boolean = false>(
  options: Options<GetNewsfeedReactionData, ThrowOnError>,
): RequestResult<
  GetNewsfeedReactionResponses,
  GetNewsfeedReactionErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetNewsfeedReactionResponses,
    GetNewsfeedReactionErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/newsfeed-reaction/{uuid}/",
    ...options,
  });

/**
 * Newsfeed scoped to a specific user
 */
export const getNewsfeedUser = <ThrowOnError extends boolean = false>(
  options: Options<GetNewsfeedUserData, ThrowOnError>,
): RequestResult<
  GetNewsfeedUserResponses,
  GetNewsfeedUserErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetNewsfeedUserResponses,
    GetNewsfeedUserErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/newsfeed-user/{uuid}/",
    ...options,
  });

/**
 * Newsfeed data for a user's profile page
 */
export const getProfileNewsfeedData = <ThrowOnError extends boolean = false>(
  options: Options<GetProfileNewsfeedDataData, ThrowOnError>,
): RequestResult<
  GetProfileNewsfeedDataResponses,
  GetProfileNewsfeedDataErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetProfileNewsfeedDataResponses,
    GetProfileNewsfeedDataErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/profile-newsfeed-data/{uuid}/",
    ...options,
  });

/**
 * Data for a single notification/feed item by id
 */
export const getSingleNotificationData = <ThrowOnError extends boolean = false>(
  options: Options<GetSingleNotificationDataData, ThrowOnError>,
): RequestResult<
  GetSingleNotificationDataResponses,
  GetSingleNotificationDataErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetSingleNotificationDataResponses,
    GetSingleNotificationDataErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/single-notification-data/{id}/",
    ...options,
  });

/**
 * Newsfeed data for the your-feed tab
 */
export const getYourNewsfeedData = <ThrowOnError extends boolean = false>(
  options: Options<GetYourNewsfeedDataData, ThrowOnError>,
): RequestResult<
  GetYourNewsfeedDataResponses,
  GetYourNewsfeedDataErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetYourNewsfeedDataResponses,
    GetYourNewsfeedDataErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/your-newsfeed-data/{uuid}/",
    ...options,
  });

/**
 * Reactions on your-feed newsfeed items
 */
export const getYourNewsfeedReaction = <ThrowOnError extends boolean = false>(
  options: Options<GetYourNewsfeedReactionData, ThrowOnError>,
): RequestResult<
  GetYourNewsfeedReactionResponses,
  GetYourNewsfeedReactionErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetYourNewsfeedReactionResponses,
    GetYourNewsfeedReactionErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/your-newsfeed-reaction/{uuid}/",
    ...options,
  });

/**
 * Config for joining a challenge
 */
export const getChallengeJoinConfig = <ThrowOnError extends boolean = false>(
  options: Options<GetChallengeJoinConfigData, ThrowOnError>,
): RequestResult<
  GetChallengeJoinConfigResponses,
  GetChallengeJoinConfigErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetChallengeJoinConfigResponses,
    GetChallengeJoinConfigErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/challenge-join-config/",
    ...options,
  });

/**
 * Share a user's challenge progress; request body not captured
 */
export const createChallengeProgressShare = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateChallengeProgressShareData, ThrowOnError>,
): RequestResult<
  CreateChallengeProgressShareResponses,
  CreateChallengeProgressShareErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateChallengeProgressShareResponses,
    CreateChallengeProgressShareErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/challenge-progress-share/{uuid}/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * A user's featured list challenges (see reference §8 PublishedList.challenge_info)
 */
export const getMyFeaturedListChallenges = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetMyFeaturedListChallengesData, ThrowOnError>,
): RequestResult<
  GetMyFeaturedListChallengesResponses,
  GetMyFeaturedListChallengesErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetMyFeaturedListChallengesResponses,
    GetMyFeaturedListChallengesErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/my-featured-list-challenges/{uuid}/",
    ...options,
  });

/**
 * Playlists available to the user
 */
export const getPlaylists = <ThrowOnError extends boolean = false>(
  options: Options<GetPlaylistsData, ThrowOnError>,
): RequestResult<GetPlaylistsResponses, GetPlaylistsErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetPlaylistsResponses,
    GetPlaylistsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/playlists/",
    ...options,
  });

/**
 * Items on a published list/guide
 */
export const getPublishedListItemNew = <ThrowOnError extends boolean = false>(
  options: Options<GetPublishedListItemNewData, ThrowOnError>,
): RequestResult<
  GetPublishedListItemNewResponses,
  GetPublishedListItemNewErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetPublishedListItemNewResponses,
    GetPublishedListItemNewErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/published-list-item-new/",
    ...options,
  });

/**
 * Published lists/guides (see reference §8 PublishedList)
 */
export const getPublishedList = <ThrowOnError extends boolean = false>(
  options: Options<GetPublishedListData, ThrowOnError>,
): RequestResult<
  GetPublishedListResponses,
  GetPublishedListErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetPublishedListResponses,
    GetPublishedListErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/published-list/",
    ...options,
  });

/**
 * Published lists/guides authored by a specific user
 */
export const getPublishedListByUser = <ThrowOnError extends boolean = false>(
  options: Options<GetPublishedListByUserData, ThrowOnError>,
): RequestResult<
  GetPublishedListByUserResponses,
  GetPublishedListByUserErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetPublishedListByUserResponses,
    GetPublishedListByUserErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/published-list/{uuid}/",
    ...options,
  });

/**
 * A user's short list (condensed guide/wishlist)
 */
export const getShortList = <ThrowOnError extends boolean = false>(
  options: Options<GetShortListData, ThrowOnError>,
): RequestResult<GetShortListResponses, GetShortListErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetShortListResponses,
    GetShortListErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/short-list/{uuid}/",
    ...options,
  });

/**
 * Closed/resolved user-guide items
 */
export const getUserGuideItemsClose = <ThrowOnError extends boolean = false>(
  options: Options<GetUserGuideItemsCloseData, ThrowOnError>,
): RequestResult<
  GetUserGuideItemsCloseResponses,
  GetUserGuideItemsCloseErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetUserGuideItemsCloseResponses,
    GetUserGuideItemsCloseErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/user-guide-items-close/",
    ...options,
  });

/**
 * Items on a user's guide
 */
export const getUserGuideItems = <ThrowOnError extends boolean = false>(
  options: Options<GetUserGuideItemsData, ThrowOnError>,
): RequestResult<
  GetUserGuideItemsResponses,
  GetUserGuideItemsErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetUserGuideItemsResponses,
    GetUserGuideItemsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/user-guide-items/",
    ...options,
  });

/**
 * A user's guide(s)
 */
export const getUserGuide = <ThrowOnError extends boolean = false>(
  options: Options<GetUserGuideData, ThrowOnError>,
): RequestResult<GetUserGuideResponses, GetUserGuideErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetUserGuideResponses,
    GetUserGuideErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/user-guide/",
    ...options,
  });

/**
 * Record placement of horizontal-scroll list modules shown to a user; request body not captured
 */
export const createUserHscrollListsPlacement = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateUserHscrollListsPlacementData, ThrowOnError>,
): RequestResult<
  CreateUserHscrollListsPlacementResponses,
  CreateUserHscrollListsPlacementErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateUserHscrollListsPlacementResponses,
    CreateUserHscrollListsPlacementErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/user-hscroll-lists/placement/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * In-app notifications for a user
 */
export const getAppNotification = <ThrowOnError extends boolean = false>(
  options: Options<GetAppNotificationData, ThrowOnError>,
): RequestResult<
  GetAppNotificationResponses,
  GetAppNotificationErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetAppNotificationResponses,
    GetAppNotificationErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/app-notification/{uuid}/",
    ...options,
  });

/**
 * Banner notification state for a user
 */
export const getBannerNotification = <ThrowOnError extends boolean = false>(
  options: Options<GetBannerNotificationData, ThrowOnError>,
): RequestResult<
  GetBannerNotificationResponses,
  GetBannerNotificationErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetBannerNotificationResponses,
    GetBannerNotificationErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/banner-notification/{uuid}/",
    ...options,
  });

/**
 * Users who have blocked this user
 */
export const getBlockedMe = <ThrowOnError extends boolean = false>(
  options: Options<GetBlockedMeData, ThrowOnError>,
): RequestResult<GetBlockedMeResponses, GetBlockedMeErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetBlockedMeResponses,
    GetBlockedMeErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/blocked-me/{uuid}/",
    ...options,
  });

/**
 * Users blocked by this user
 */
export const getBlocked = <ThrowOnError extends boolean = false>(
  options: Options<GetBlockedData, ThrowOnError>,
): RequestResult<GetBlockedResponses, GetBlockedErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetBlockedResponses,
    GetBlockedErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/blocked/{uuid}/",
    ...options,
  });

/**
 * Count of unread in-app notifications
 */
export const getCountAppNotificationUnread = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetCountAppNotificationUnreadData, ThrowOnError>,
): RequestResult<
  GetCountAppNotificationUnreadResponses,
  GetCountAppNotificationUnreadErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetCountAppNotificationUnreadResponses,
    GetCountAppNotificationUnreadErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/count-app-notification-unread/",
    ...options,
  });

/**
 * Mark a user's notifications as read (observed as a GET request)
 */
export const getMarkRead = <ThrowOnError extends boolean = false>(
  options: Options<GetMarkReadData, ThrowOnError>,
): RequestResult<GetMarkReadResponses, GetMarkReadErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetMarkReadResponses,
    GetMarkReadErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/mark-read/{uuid}/",
    ...options,
  });

/**
 * Users muted by this user
 */
export const getMuted = <ThrowOnError extends boolean = false>(
  options: Options<GetMutedData, ThrowOnError>,
): RequestResult<GetMutedResponses, GetMutedErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetMutedResponses,
    GetMutedErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/muted/{uuid}/",
    ...options,
  });

/**
 * Comment count on a notification/feed item
 */
export const getNotificationCommentCount = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetNotificationCommentCountData, ThrowOnError>,
): RequestResult<
  GetNotificationCommentCountResponses,
  GetNotificationCommentCountErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetNotificationCommentCountResponses,
    GetNotificationCommentCountErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/notification-comment-count/{id}/",
    ...options,
  });

/**
 * Reactions on notifications
 */
export const getNotificationReaction = <ThrowOnError extends boolean = false>(
  options: Options<GetNotificationReactionData, ThrowOnError>,
): RequestResult<
  GetNotificationReactionResponses,
  GetNotificationReactionErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetNotificationReactionResponses,
    GetNotificationReactionErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/notification-reaction/",
    ...options,
  });

/**
 * Update a notification (e.g. mark read/dismissed); request body not fully captured
 */
export const updateNotification = <ThrowOnError extends boolean = false>(
  options: Options<UpdateNotificationData, ThrowOnError>,
): RequestResult<
  UpdateNotificationResponses,
  UpdateNotificationErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    UpdateNotificationResponses,
    UpdateNotificationErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/notification/{id}/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * In-app popup(s) queued for a user
 */
export const getPopup = <ThrowOnError extends boolean = false>(
  options: Options<GetPopupData, ThrowOnError>,
): RequestResult<GetPopupResponses, GetPopupErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetPopupResponses,
    GetPopupErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/popup/{uuid}/",
    ...options,
  });

/**
 * Available reservation slots for a business
 */
export const getAvailableReservations = <ThrowOnError extends boolean = false>(
  options: Options<GetAvailableReservationsData, ThrowOnError>,
): RequestResult<
  GetAvailableReservationsResponses,
  GetAvailableReservationsErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetAvailableReservationsResponses,
    GetAvailableReservationsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/available-reservations/{uuid}/",
    ...options,
  });

/**
 * Businesses with booked reservations
 */
export const getBusinessResBookedList = <ThrowOnError extends boolean = false>(
  options: Options<GetBusinessResBookedListData, ThrowOnError>,
): RequestResult<
  GetBusinessResBookedListResponses,
  GetBusinessResBookedListErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetBusinessResBookedListResponses,
    GetBusinessResBookedListErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/business-res-booked-list/",
    ...options,
  });

/**
 * Reservation availability for one or more businesses (response keyed by composite string per reference §5/§8 ReservationOffer)
 *
 */
export const createBusinessesResAvailability = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateBusinessesResAvailabilityData, ThrowOnError>,
): RequestResult<
  CreateBusinessesResAvailabilityResponses,
  CreateBusinessesResAvailabilityErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateBusinessesResAvailabilityResponses,
    CreateBusinessesResAvailabilityErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/businesses-res-availability/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * A user's reservation priority data
 */
export const getResPriorityData = <ThrowOnError extends boolean = false>(
  options: Options<GetResPriorityDataData, ThrowOnError>,
): RequestResult<
  GetResPriorityDataResponses,
  GetResPriorityDataErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetResPriorityDataResponses,
    GetResPriorityDataErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/res-priority-data/",
    ...options,
  });

/**
 * Options for reporting a reservation issue
 */
export const getResReportIssueOptions = <ThrowOnError extends boolean = false>(
  options: Options<GetResReportIssueOptionsData, ThrowOnError>,
): RequestResult<
  GetResReportIssueOptionsResponses,
  GetResReportIssueOptionsErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetResReportIssueOptionsResponses,
    GetResReportIssueOptionsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/res-report-issue-options/",
    ...options,
  });

/**
 * Reservation posting(s) (see reference §8 ReservationOffer)
 */
export const getReservationPosting = <ThrowOnError extends boolean = false>(
  options: Options<GetReservationPostingData, ThrowOnError>,
): RequestResult<
  GetReservationPostingResponses,
  GetReservationPostingErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetReservationPostingResponses,
    GetReservationPostingErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/reservation-posting/",
    ...options,
  });

/**
 * Reservations claimed today
 */
export const getReservationsClaimedToday = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetReservationsClaimedTodayData, ThrowOnError>,
): RequestResult<
  GetReservationsClaimedTodayResponses,
  GetReservationsClaimedTodayErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetReservationsClaimedTodayResponses,
    GetReservationsClaimedTodayErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/reservations-claimed-today/",
    ...options,
  });

/**
 * Apple Maps access token for embedded maps
 */
export const getAppleMapsToken = <ThrowOnError extends boolean = false>(
  options: Options<GetAppleMapsTokenData, ThrowOnError>,
): RequestResult<
  GetAppleMapsTokenResponses,
  GetAppleMapsTokenErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetAppleMapsTokenResponses,
    GetAppleMapsTokenErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/apple-maps-token/",
    ...options,
  });

/**
 * A user's saved Stripe payment methods
 */
export const getStripePaymentMethods = <ThrowOnError extends boolean = false>(
  options: Options<GetStripePaymentMethodsData, ThrowOnError>,
): RequestResult<
  GetStripePaymentMethodsResponses,
  GetStripePaymentMethodsErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetStripePaymentMethodsResponses,
    GetStripePaymentMethodsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/stripe-payment-methods/",
    ...options,
  });

/**
 * Fire-and-forget analytics event sink. Reference §7 lists this path on both the ACTIVITY host (row 136) and the ONBOARD host (row 135, observed during login, H3-login) — OpenAPI paths are host-agnostic and cannot be duplicated, so this single operation is modeled on the ACTIVITY host; it is also accepted on https://backoffice-service-onboarding-t57o3dxfca-nn.a.run.app during login.
 *
 */
export const createActivity = <ThrowOnError extends boolean = false>(
  options: Options<CreateActivityData, ThrowOnError>,
): RequestResult<CreateActivityResponses, CreateActivityErrors, ThrowOnError> =>
  (options.client ?? client).post<
    CreateActivityResponses,
    CreateActivityErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/activity/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Fire-and-forget client-error reporting sink
 */
export const createApiError = <ThrowOnError extends boolean = false>(
  options: Options<CreateApiErrorData, ThrowOnError>,
): RequestResult<CreateApiErrorResponses, CreateApiErrorErrors, ThrowOnError> =>
  (options.client ?? client).post<
    CreateApiErrorResponses,
    CreateApiErrorErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/api-error/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
